apiVersion: v1
kind: Service
metadata:
  name: simple-client-service
  namespace: lb-demo
spec:
  selector:
    app: simple-client-service
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30082
    - name: debug
      protocol: TCP
      port: 5005
      targetPort: 5005
      nodePort: 30105
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-client-service-zone-a
  namespace: lb-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-client-service
      zone: zone-a
  template:
    metadata:
      labels:
        app: simple-client-service
        zone: zone-a
    spec:
      serviceAccountName: spring-cloud-kubernetes
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - zone-a
      containers:
        - name: simple-client-service
          image: simple-client-service:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8081
            - name: debug
              containerPort: 5005
          env:
            - name: ZONE
              value: "zone-a"
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-client-service-zone-b
  namespace: lb-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-client-service
      zone: zone-b
  template:
    metadata:
      labels:
        app: simple-client-service
        zone: zone-b
    spec:
      serviceAccountName: spring-cloud-kubernetes
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - zone-b
      containers:
        - name: simple-client-service
          image: simple-client-service:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8081
            - name: debug
              containerPort: 5005
          env:
            - name: ZONE
              value: "zone-b"
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

